CREATE TABLE POLESTAR_SCHEDULES (
  ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME        VARCHAR(128) NOT NULL,
  CRON        VARCHAR(32)  NOT NULL,
  COMMAND     TEXT         NOT NULL,
  ENABLED     BIT(1)       NOT NULL DEFAULT 1,
  CREATE_TIME TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IX_POLESTAR_SCHEDULES_ENABLED ON POLESTAR_SCHEDULES (ENABLED);
